services:
  - type: web
    name: sigp-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /docs
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SIGP_SEDE_CLINICA_ID
        sync: false
      - key: SIGP_ADMIN_USER_ID
        sync: false
      - key: SIGP_ENFERMERIA_USER_ID
        sync: false
      - key: SIGP_MEDICO_USER_ID
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
