import { LoaderCircle, Search, Stethoscope } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { getApiUrl, getAuthHeaders } from '../../lib/auth';

export function DoctorPatientSearch() {
  const navigate = useNavigate(); const [query, setQuery] = useState(''); const [results, setResults] = useState<Array<{ id: string; name: string; dni: string }>>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  async function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (query.trim().length < 2) { setMessage('Ingresá al menos 2 caracteres.'); return; } setLoading(true); setMessage(''); try { const response = await fetch(`${getApiUrl()}/pacientes/buscar?${new URLSearchParams({ q: query.trim() })}`, { headers: getAuthHeaders() }); const body = await response.json(); const patients = Array.isArray(body.pacientes) ? body.pacientes : []; setResults(patients.map((p: { id: string; nombre?: string; apellido?: string; dni?: string }) => ({ id: p.id, name: [p.nombre, p.apellido].filter(Boolean).join(' ') || 'Paciente sin identificar', dni: p.dni || 'Sin DNI' }))); if (!patients.length) setMessage('No se encontraron pacientes con esos datos.'); } catch { setMessage('No se pudo buscar pacientes.'); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-slate-100 px-5 py-10 text-slate-800"><section className="mx-auto max-w-3xl rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-md bg-blue-700 text-white"><Stethoscope size={21} /></span><div><h1 className="text-2xl font-bold text-slate-900">Historia Clínica Digital</h1><p className="text-sm text-slate-500">Seleccioná un paciente para iniciar la atención médica.</p></div></div><form className="mt-6 flex gap-2" onSubmit={search}><input className="flex-1 rounded-md border border-slate-300 px-3 py-3" value={query} onChange={e => setQuery(e.target.value)} placeholder="DNI o nombre del paciente" /><button className="rounded-md bg-blue-700 px-5 text-sm font-semibold text-white" disabled={loading}>{loading ? <LoaderCircle className="animate-spin" size={18} /> : <Search size={18} />}</button></form>{message && <p className="mt-3 text-sm text-slate-600">{message}</p>}<div className="mt-5 space-y-2">{results.map(patient => <button className="flex w-full items-center justify-between rounded-lg border border-slate-200 p-4 text-left hover:border-blue-400 hover:bg-blue-50" key={patient.id} onClick={() => navigate(`/hcd/${patient.id}`)}><span><strong className="block">{patient.name}</strong><small className="text-slate-500">DNI {patient.dni}</small></span><span className="text-sm font-semibold text-blue-700">Abrir HCD</span></button>)}</div></section></main>;
}
