import { AlertTriangle, CheckCircle2, ClipboardPenLine, LoaderCircle, Search, ShieldCheck, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useParams } from 'react-router-dom';
import { getApiUrl, getAuthHeaders } from '../../lib/auth';

type Tab = 'curves' | 'consultation' | 'prescription';
type Risk = 'low' | 'warning' | 'critical' | 'unknown';
interface Patient { id: string; name: string; dni: string; age: string; history: string[]; }
interface GrowthPoint { date: string; value: number; }
interface HcdData { patient: Patient; curves: Record<'peso' | 'talla' | 'perimetro_cefalico', GrowthPoint[]>; }
interface Drug { id: string; name: string; risk: Risk; detail: string; }
interface Prescription { id: string; name: string; risk: Risk; dose: string; frequency: string; duration: string; }

const curveMetadata = { peso: { title: 'Peso', unit: 'kg', color: '#E53E3E' }, talla: { title: 'Talla', unit: 'cm', color: '#38A169' }, perimetro_cefalico: { title: 'Perímetro cefálico', unit: 'cm', color: '#6B46C1' } } as const;

function record(value: unknown): Record<string, unknown> { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function text(value: unknown, fallback = '') { return typeof value === 'string' || typeof value === 'number' ? String(value) : fallback; }
function numberValue(value: unknown) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : null; }
function details(value: unknown): string[] { if (Array.isArray(value)) return value.map((item) => text(item)).filter(Boolean); if (typeof value === 'string') return value ? [value] : []; const values = Object.values(record(value)).map((item) => text(item)).filter(Boolean); return values; }

function normalizeCurve(value: unknown, metric: 'peso' | 'talla' | 'perimetro_cefalico'): GrowthPoint[] {
  if (!Array.isArray(value)) return [];
  const valueKeys = metric === 'peso' ? ['valor', 'peso', 'peso_kg', 'value'] : metric === 'talla' ? ['valor', 'talla', 'talla_cm', 'value'] : ['valor', 'perimetro_cefalico', 'perimetro_cefalico_cm', 'value'];
  return value.flatMap((item) => { const source = record(item); const measurement = valueKeys.map((key) => numberValue(source[key])).find((current): current is number => current !== null); const date = text(source.fecha ?? source.fecha_hora ?? source.date); return measurement === undefined || !date ? [] : [{ date, value: measurement }]; });
}

function normalizeHcd(payload: unknown, patientId: string): HcdData {
  const source = record(payload); const rawPatient = record(source.paciente); const inferredName = [text(rawPatient.nombre), text(rawPatient.apellido)].filter(Boolean).join(' ');
  const curves = record(source.curvas_crecimiento);
  return { patient: { id: text(rawPatient.id ?? source.paciente_id, patientId), name: (text(rawPatient.nombre_completo) || inferredName || 'Paciente sin identificar'), dni: text(rawPatient.dni, 'Sin DNI'), age: text(rawPatient.edad, ''), history: details(source.antecedentes ?? rawPatient.antecedentes) }, curves: { peso: normalizeCurve(curves.peso, 'peso'), talla: normalizeCurve(curves.talla, 'talla'), perimetro_cefalico: normalizeCurve(curves.perimetro_cefalico, 'perimetro_cefalico') } };
}

function normalizeRisk(value: unknown): Risk { const risk = text(value).toLowerCase(); return risk === 'low' || risk === 'warning' || risk === 'critical' ? risk : 'unknown'; }
function drugsFrom(payload: unknown): Drug[] { const source = record(payload); const rows = Array.isArray(payload) ? payload : Array.isArray(source.resultados) ? source.resultados : Array.isArray(source.medicamentos) ? source.medicamentos : []; return rows.flatMap((item, index) => { const drug = record(item); const name = text(drug.nombre ?? drug.name); return name ? [{ id: text(drug.id, `${name}-${index}`), name, risk: normalizeRisk(drug.risk), detail: text(drug.detail ?? drug.descripcion ?? drug.advertencia) }] : []; }); }
function responseError(payload: unknown) { const detail = record(payload).detail; return typeof detail === 'string' ? detail : 'No se pudo completar la operación.'; }

export function DoctorView() {
  const { pacienteId } = useParams();
  const [hcd, setHcd] = useState<HcdData | null>(null);
  const [tab, setTab] = useState<Tab>('curves');
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [motivo, setMotivo] = useState(''); const [diagnostico, setDiagnostico] = useState(''); const [plan, setPlan] = useState('');
  const [prescriptions, setPrescriptions] = useState<Prescription[]>([]);
  const [signature, setSignature] = useState(false); const [isSaving, setIsSaving] = useState(false); const [message, setMessage] = useState<{ type: 'error' | 'success'; text: string } | null>(null);
  const [drugQuery, setDrugQuery] = useState(''); const [drugResults, setDrugResults] = useState<Drug[]>([]); const [isSearchingDrug, setIsSearchingDrug] = useState(false); const [drugError, setDrugError] = useState<string | null>(null);

  useEffect(() => { if (!pacienteId) return; const confirmedPatientId = pacienteId; const controller = new AbortController(); async function loadHcd() { setIsLoading(true); setLoadError(null); try { const response = await fetch(`${getApiUrl()}/pacientes/${encodeURIComponent(confirmedPatientId)}/hcd`, { headers: getAuthHeaders(), signal: controller.signal }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(responseError(payload)); setHcd(normalizeHcd(payload, confirmedPatientId)); } catch (caughtError) { if (caughtError instanceof DOMException && caughtError.name === 'AbortError') return; setLoadError(caughtError instanceof Error ? caughtError.message : 'No se pudo cargar la historia clínica.'); } finally { if (!controller.signal.aborted) setIsLoading(false); } } void loadHcd(); return () => controller.abort(); }, [pacienteId]);

  const patient = hcd?.patient;
  const hasCriticalRisk = prescriptions.some((prescription) => prescription.risk === 'critical');
  const sortedCurves = useMemo(() => hcd ? Object.fromEntries(Object.entries(hcd.curves).map(([metric, points]) => [metric, [...points].sort((a, b) => a.date.localeCompare(b.date))])) as HcdData['curves'] : null, [hcd]);

  async function searchDrugs(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const activePatientId = patient?.id; if (!drugQuery.trim() || !activePatientId) return; setIsSearchingDrug(true); setDrugError(null); setDrugResults([]); try { const params = new URLSearchParams({ q: drugQuery.trim(), paciente_id: activePatientId }); const response = await fetch(`${getApiUrl()}/vademecum/buscar?${params}`, { headers: getAuthHeaders() }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(responseError(payload)); const results = drugsFrom(payload); setDrugResults(results); if (!results.length) setDrugError('No se encontraron medicamentos para esa búsqueda.'); } catch (caughtError) { setDrugError(caughtError instanceof Error ? caughtError.message : 'No se pudo consultar el vademécum.'); } finally { setIsSearchingDrug(false); } }
  function addDrug(drug: Drug) { if (prescriptions.some((item) => item.id === drug.id)) return; setPrescriptions((current) => [...current, { ...drug, dose: '', frequency: '', duration: '' }]); setDrugResults([]); setDrugQuery(''); }
  function updatePrescription(id: string, field: 'dose' | 'frequency' | 'duration', value: string) { setPrescriptions((current) => current.map((item) => item.id === id ? { ...item, [field]: value } : item)); }

  async function saveConsultation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const activePatientId = patient?.id; if (!activePatientId) return; if (!motivo.trim() || !diagnostico.trim() || !plan.trim()) { setMessage({ type: 'error', text: 'Completá motivo, diagnóstico y plan terapéutico.' }); return; } if (!signature) { setMessage({ type: 'error', text: 'Debés confirmar la firma digital para cerrar la consulta.' }); return; } if (prescriptions.some((item) => !item.dose.trim() || !item.frequency.trim() || !item.duration.trim())) { setMessage({ type: 'error', text: 'Completá dosis, frecuencia y duración de cada prescripción.' }); return; } setIsSaving(true); setMessage(null); try { const headers = new Headers(getAuthHeaders()); headers.set('Content-Type', 'application/json'); const response = await fetch(`${getApiUrl()}/hcd/${encodeURIComponent(activePatientId)}/consultas`, { method: 'POST', headers, body: JSON.stringify({ motivo, diagnostico, plan, prescripciones: prescriptions.map(({ name, dose, frequency, duration }) => ({ nombre: name, dosis: dose, frecuencia: frequency, duracion: duration })), firma_digital: true }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(responseError(payload)); setMessage({ type: 'success', text: 'Consulta guardada y firmada digitalmente.' }); setMotivo(''); setDiagnostico(''); setPlan(''); setPrescriptions([]); setSignature(false); } catch (caughtError) { setMessage({ type: 'error', text: caughtError instanceof Error ? caughtError.message : 'No se pudo guardar la consulta.' }); } finally { setIsSaving(false); } }

  if (!pacienteId) return <CenteredMessage text="No se indicó un paciente para consultar." />;
  if (isLoading) return <CenteredMessage text="Cargando historia clínica…" loading />;
  if (loadError || !hcd || !patient) return <CenteredMessage text={loadError ?? 'No se encontró la historia clínica.'} />;
  return <main className="min-h-screen bg-slate-100 text-slate-800"><header className="border-b border-slate-200 bg-white px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-7xl items-center gap-3"><span className="grid size-9 place-items-center rounded-md bg-blue-700 text-white"><ShieldCheck size={20} /></span><div><p className="text-lg font-bold leading-none text-slate-900">SIGP</p><p className="mt-1 text-[10px] font-medium tracking-wide text-slate-500">HISTORIA CLÍNICA DIGITAL</p></div></div></header><section className="mx-auto max-w-7xl px-5 py-7 sm:px-8"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-sm text-slate-500">Paciente activo</p><h1 className="mt-1 text-2xl font-bold text-slate-900">{patient.name}</h1><p className="mt-1 font-mono text-sm text-slate-500">DNI {patient.dni}{patient.age ? ` · ${patient.age}` : ''}</p></div><span className="inline-flex w-fit items-center gap-2 rounded-md bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-700"><ClipboardPenLine size={17} />Consulta clínica</span></div>{patient.history.length > 0 && <div className="mt-4 border-t border-slate-100 pt-4"><p className="text-sm font-semibold text-slate-700">Antecedentes</p><ul className="mt-2 flex flex-wrap gap-2">{patient.history.map((item, index) => <li key={`${item}-${index}`} className="rounded-md bg-red-50 px-2.5 py-1 text-xs font-medium text-red-700">{item}</li>)}</ul></div>}</div>
    <nav className="mt-5 flex gap-2 border-b border-slate-300" aria-label="Secciones de historia clínica"><TabButton active={tab === 'curves'} onClick={() => setTab('curves')}>Curvas de desarrollo</TabButton><TabButton active={tab === 'consultation'} onClick={() => setTab('consultation')}>Registro de consulta</TabButton><TabButton active={tab === 'prescription'} onClick={() => setTab('prescription')}>Prescripción</TabButton></nav>
    {tab === 'curves' && <section className="mt-5 grid gap-4 lg:grid-cols-3">{(Object.keys(curveMetadata) as Array<keyof typeof curveMetadata>).map((metric) => <GrowthChart key={metric} title={curveMetadata[metric].title} unit={curveMetadata[metric].unit} color={curveMetadata[metric].color} points={sortedCurves?.[metric] ?? []} />)}</section>}
    {tab === 'prescription' && <section className="mt-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-900">Validación de medicamentos</h2><p className="mt-1 text-sm text-slate-500">Consultá el vademécum antes de incorporar un fármaco a la receta.</p><form className="mt-4 flex flex-col gap-2 sm:flex-row" onSubmit={searchDrugs}><input className="flex-1 rounded-md border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100" value={drugQuery} onChange={(event) => setDrugQuery(event.target.value)} placeholder="Buscar medicamento" /><button className="inline-flex items-center justify-center gap-2 rounded-md bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" type="submit" disabled={isSearchingDrug}>{isSearchingDrug && <LoaderCircle className="animate-spin" size={16} />}<Search size={16} />Validar</button></form>{drugError && <p className="mt-3 text-sm text-red-700">{drugError}</p>}{drugResults.length > 0 && <div className="mt-4 divide-y rounded-md border border-slate-200">{drugResults.map((drug) => <button className="flex w-full items-center justify-between gap-3 p-3 text-left hover:bg-slate-50" type="button" key={drug.id} onClick={() => addDrug(drug)}><span><strong className="block text-sm">{drug.name}</strong>{drug.detail && <span className="text-xs text-slate-500">{drug.detail}</span>}</span><RiskBadge risk={drug.risk} /></button>)}</div>}<PrescriptionEditor items={prescriptions} onUpdate={updatePrescription} onRemove={(id) => setPrescriptions((current) => current.filter((item) => item.id !== id))} /></section>}
    {tab === 'consultation' && <section className="mt-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><form onSubmit={saveConsultation}><h2 className="text-lg font-bold text-slate-900">Registro de consulta</h2><div className="mt-4 grid gap-4"><TextArea label="Motivo de consulta" value={motivo} onChange={setMotivo} /><TextArea label="Diagnóstico" value={diagnostico} onChange={setDiagnostico} /><TextArea label="Plan terapéutico" value={plan} onChange={setPlan} /></div><div className="mt-5 rounded-md border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-semibold text-slate-700">Prescripciones incorporadas: {prescriptions.length}</p>{hasCriticalRisk && <p className="mt-2 flex items-center gap-2 text-sm font-semibold text-red-700"><AlertTriangle size={17} />Existe una prescripción con riesgo crítico.</p>}<button className="mt-3 text-sm font-semibold text-blue-700 hover:text-blue-800" type="button" onClick={() => setTab('prescription')}>Gestionar prescripciones</button></div><label className="mt-5 flex cursor-pointer items-start gap-3 text-sm text-slate-700"><input className="mt-1 size-4 accent-blue-700" type="checkbox" checked={signature} onChange={(event) => setSignature(event.target.checked)} /><span><strong className="block">Firmar digitalmente esta consulta</strong>Confirmo que la información clínica registrada es correcta.</span></label>{message && <p className={`mt-4 rounded-md border px-3 py-2 text-sm ${message.type === 'success' ? 'border-green-200 bg-green-50 text-green-700' : 'border-red-200 bg-red-50 text-red-700'}`} role="alert">{message.text}</p>}<button className="mt-5 inline-flex items-center gap-2 rounded-md bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60" type="submit" disabled={isSaving}>{isSaving ? <LoaderCircle className="animate-spin" size={18} /> : <CheckCircle2 size={18} />}{isSaving ? 'Guardando…' : 'Guardar y firmar digitalmente'}</button></form></section>}
  </section></main>;
}

function CenteredMessage({ text, loading = false }: { text: string; loading?: boolean }) { return <main className="grid min-h-screen place-items-center bg-slate-100 p-6"><p className="flex items-center gap-2 rounded-lg bg-white p-5 text-slate-700 shadow-sm">{loading && <LoaderCircle className="animate-spin text-blue-700" size={19} />}{text}</p></main>; }
function TabButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: string }) { return <button className={`border-b-2 px-3 py-3 text-sm font-semibold ${active ? 'border-blue-700 text-blue-700' : 'border-transparent text-slate-500 hover:text-slate-800'}`} type="button" onClick={onClick}>{children}</button>; }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-semibold text-slate-700">{label}<textarea className="mt-2 min-h-24 w-full rounded-md border border-slate-300 p-3 text-sm font-normal outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function RiskBadge({ risk }: { risk: Risk }) { const styles = { low: 'bg-green-50 text-green-700', warning: 'bg-orange-50 text-orange-700', critical: 'bg-red-50 text-red-700', unknown: 'bg-slate-100 text-slate-600' }; const labels = { low: 'Sin riesgo', warning: 'Precaución', critical: 'Riesgo crítico', unknown: 'Sin dato' }; return <span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${styles[risk]}`}>{labels[risk]}</span>; }
function PrescriptionEditor({ items, onUpdate, onRemove }: { items: Prescription[]; onUpdate: (id: string, field: 'dose' | 'frequency' | 'duration', value: string) => void; onRemove: (id: string) => void }) { return items.length ? <div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="py-2 pr-3">Medicamento</th><th className="py-2 pr-3">Dosis</th><th className="py-2 pr-3">Frecuencia</th><th className="py-2 pr-3">Duración</th><th /></tr></thead><tbody>{items.map((item) => <tr className="border-t border-slate-100" key={item.id}><td className="py-3 pr-3"><strong>{item.name}</strong><span className="mt-1 block"><RiskBadge risk={item.risk} /></span></td><td className="py-3 pr-3"><input className="w-28 rounded border border-slate-300 px-2 py-1.5" value={item.dose} onChange={(event) => onUpdate(item.id, 'dose', event.target.value)} placeholder="Ej. 5 ml" /></td><td className="py-3 pr-3"><input className="w-32 rounded border border-slate-300 px-2 py-1.5" value={item.frequency} onChange={(event) => onUpdate(item.id, 'frequency', event.target.value)} placeholder="Cada 8 hs" /></td><td className="py-3 pr-3"><input className="w-28 rounded border border-slate-300 px-2 py-1.5" value={item.duration} onChange={(event) => onUpdate(item.id, 'duration', event.target.value)} placeholder="5 días" /></td><td className="py-3"><button className="rounded p-2 text-red-600 hover:bg-red-50" type="button" onClick={() => onRemove(item.id)} aria-label={`Quitar ${item.name}`}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div> : <p className="mt-5 text-sm text-slate-500">Todavía no agregaste medicamentos a la prescripción.</p>; }
function GrowthChart({ title, unit, color, points }: { title: string; unit: string; color: string; points: GrowthPoint[] }) { return <article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-baseline justify-between"><h2 className="font-bold text-slate-900">{title}</h2><span className="text-xs text-slate-500">{points.length ? `${points.at(-1)?.value} ${unit}` : 'Sin mediciones'}</span></div><div className="mt-4 h-52">{points.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={points}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} width={30} /><Tooltip /><Line type="monotone" dataKey="value" stroke={color} strokeWidth={2.5} dot={{ r: 3 }} /></LineChart></ResponsiveContainer> : <div className="grid h-full place-items-center rounded-md bg-slate-50 text-sm text-slate-500">No hay mediciones disponibles.</div>}</div></article>; }
